version: "3"

services:
  dependencies:
    build:
      context: ./images/dependencies
    volumes:
#      - ~/.m2:/src
      - ./libs:/src
      - ./report/libs:/report
    environment:
      PROJECT_NAME: "test"
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./data/sonar/conf:/opt/sonarqube/conf
      - ./data/sonar/data:/opt/sonarqube/data
      - ./data/sonar/extensions:/opt/sonarqube/extensions
      - ./data/sonar/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./data/postgres:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./data/postgres-data:/var/lib/postgresql/data
